---
- name: Изменение имени хоста и установка стандартных пакетов
  hosts: all
  roles:
    - role: default_packages
  tags:
    - install_packages

- name: Установка и настройка nginx c кастомной страницей
  hosts: vm-02, vm-03, vm-04  # Будет работать на узлах в группе corps
  roles:
    - role: nginx_custom
  tags:
    - nginx_custom

- name: Настройка проксирующего Nginx
  hosts: vm-02  # Применяем только к vm-02 (прокси-серверу)
  roles:
    - role: nginx_proxy
  tags:
    - nginx_proxy